obj-$(CONFIG_USE_OF) += board-dt.o
obj-$(CONFIG_SMP)	+= platsmp.o
obj-$(CONFIG_ARCH_QCS405) += board-qcs405.o
obj-$(CONFIG_ARCH_SDXPRAIRIE) += board-sdxprairie.o
obj-$(CONFIG_ARCH_MSM8974) += board-msm8974.o